name: CI/CD Frontend Pipeline

on:
  push:
    branches:
      - dev
    paths:
      - frontend/**
      - docker/frontend/**
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml

jobs:
  build:
    name: Build, Push, and Deploy Frontend on Local Docker Desktop
    runs-on: self-hosted  # Ensure the runner is running locally as a service

    env:
      REGISTRY: docker.io
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/streaming-music-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest -f ./docker/frontend/Dockerfile .
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Pull and Run Docker Container Locally
        run: |
          IMAGE_NAME="$REGISTRY/$IMAGE_NAME:latest"

          # Pull the latest image
          docker pull $IMAGE_NAME

          # Stop and remove any existing container
          docker stop streaming-music-frontend || true
          docker rm streaming-music-frontend || true

          # Run the new container
          docker run -d -p 3000:3000 --name streaming-music-frontend $IMAGE_NAME

          echo "Deployment complete on Docker Desktop!"
